/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

/**
 *
 * @author marcelo
 */
/**
 * Venda generated by hbm2java
 */
public class VendaFbase implements java.io.Serializable {

    private int id;
    private String nome;
    private Integer qtd;
    private Double valor;
    private String cod;

    public VendaFbase() {
    }

    public VendaFbase(int id) {
        this.id = id;
    }

    public VendaFbase(int id, String nome, Integer qtd, Double valor, String cod) {
        this.id = id;
        this.nome = nome;
        this.qtd = qtd;
        this.valor = valor;
        this.cod = cod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getQtd() {
        return this.qtd;
    }

    public void setQtd(Integer qtd) {
        this.qtd = qtd;
    }

    public Double getValor() {
        return this.valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public String getCod() {
        return this.cod;
    }

    public void setCod(String cod) {
        this.cod = cod;
    }

}
