package javaapp;
// Generated Jun 27, 2020 2:23:44 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Venda generated by hbm2java
 */
@Entity(name = "Venda")
@Table(name = "venda")
public class Venda implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String nome;
    private Integer qtd;
    private BigDecimal valor;
    private String cod;

    public Venda() {
    }

    public Venda(int id) {
        this.id = id;
    }

    public Venda(int id, String nome, Integer qtd, BigDecimal valor, String cod) {
        this.id = id;
        this.nome = nome;
        this.qtd = qtd;
        this.valor = valor;
        this.cod = cod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getQtd() {
        return this.qtd;
    }

    public void setQtd(Integer qtd) {
        this.qtd = qtd;
    }

    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public String getCod() {
        return this.cod;
    }

    public void setCod(String cod) {
        this.cod = cod;
    }

}
